### ISSUE TITLE
Error running star.java: SQL error or missing database (no such column: c1_0.net_user_id

### ISSUE THREAD

**Issue by Sebakan** [hykilpikonna/AquaDX#51]
After all the instalation and having running the db on docker, once I run the start.bat I got this after a while:

```
←[32m :: Spring Boot :: ←[39m              ←[2m (v3.2.3)←[0;39m

←[35m08-15 21:17:28←[0;39m ←[32mINFO ←[0;39m ←[94mENTRYK←[0;39m | ←[94mEntryKt                                 ←[0;39m : Starting EntryKt v1.0.0 using Java 21.0.3 with PID 1028 (G:\Emulators\Chunithm\aqua-0.0.47\AquaDX\aqua.jar started by Sebastian in G:\Emulators\Chunithm\aqua-0.0.47\AquaDX)
←[35m08-15 21:17:28←[0;39m ←[32mINFO ←[0;39m ←[94mENTRYK←[0;39m | ←[94mEntryKt                                 ←[0;39m : No active profile set, falling back to 1 default profile: "default"
←[35m08-15 21:17:30←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37m.s.d.r.c.RepositoryConfigurationDelegate←[0;39m : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
←[35m08-15 21:17:31←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37m.s.d.r.c.RepositoryConfigurationDelegate←[0;39m : Finished Spring Data repository scanning in 610 ms. Found 155 JPA repository interfaces.
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.s.b.w.e.j.JettyServletWebServerFactory←[0;39m : Server initialized with port: 80
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37morg.eclipse.jetty.server.Server         ←[0;39m : jetty-12.0.6; built: 2024-01-30T02:43:24.387Z; git: 78ab6e6ba163f89cdd97f2ae0283fbb5e371cfaf; jvm 21.0.3+7-LTS-152
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.e.j.s.h.ContextHandler.application    ←[0;39m : Initializing Spring embedded WebApplicationContext
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mw.s.c.ServletWebServerApplicationContext←[0;39m : Root WebApplicationContext: initialization completed in 3758 ms
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.e.j.session.DefaultSessionIdManager   ←[0;39m : Session workerName=node0
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.e.jetty.server.handler.ContextHandler ←[0;39m : Started osbwej.JettyEmbeddedWebAppContext@40fd1a78{application,/,b=file:/C:/Users/Sebastian/AppData/Local/Temp/jetty-docbase.80.4833982340918080819/,a=AVAILABLE,h=oeje10s.SessionHandler@53b7f08{STARTED}}
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.e.j.e.servlet.ServletContextHandler   ←[0;39m : Started osbwej.JettyEmbeddedWebAppContext@40fd1a78{application,/,b=file:/C:/Users/Sebastian/AppData/Local/Temp/jetty-docbase.80.4833982340918080819/,a=AVAILABLE,h=oeje10s.SessionHandler@53b7f08{STARTED}}
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37morg.eclipse.jetty.server.Server         ←[0;39m : Started oejs.Server@2352c21f{STARTING}[12.0.6,sto=0] @6639ms
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mcom.zaxxer.hikari.HikariDataSource      ←[0;39m : HikariPool-1 - Starting...
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mcom.zaxxer.hikari.pool.HikariPool       ←[0;39m : HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@14580edc
←[35m08-15 21:17:32←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mcom.zaxxer.hikari.HikariDataSource      ←[0;39m : HikariPool-1 - Start completed.
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37morg.flywaydb.core.FlywayExecutor        ←[0;39m : Database: jdbc:sqlite:data/db.sqlite (SQLite 3.45)
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.f.core.internal.command.DbMigrate     ←[0;39m : Current version of schema "main": 259
←[35m08-15 21:17:33←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.f.core.internal.command.DbMigrate     ←[0;39m : outOfOrder mode is active. Migration of schema "main" may not be reproducible.
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.f.core.internal.command.DbMigrate     ←[0;39m : Schema "main" is up to date. No migration necessary.
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.hibernate.jpa.internal.util.LogHelper ←[0;39m : HHH000204: Processing PersistenceUnitInfo [name: default]
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37morg.hibernate.Version                   ←[0;39m : HHH000412: Hibernate ORM core version 6.4.4.Final
←[35m08-15 21:17:33←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.h.c.internal.RegionFactoryInitiator   ←[0;39m : HHH000026: Second-level cache disabled
←[35m08-15 21:17:34←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.s.o.j.p.SpringPersistenceUnitInfo     ←[0;39m : No LoadTimeWeaver setup: ignoring JPA class transformer
←[35m08-15 21:17:37←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.h.e.t.j.p.i.JtaPlatformInitiator      ←[0;39m : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
←[35m08-15 21:17:37←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mj.LocalContainerEntityManagerFactoryBean←[0;39m : Initialized JPA EntityManagerFactory for persistence unit 'default'
←[35m08-15 21:17:37←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.s.d.j.r.query.QueryEnhancerFactory    ←[0;39m : Hibernate is in classpath; If applicable, HQL parser will be used.
←[35m08-15 21:17:41←[0;39m ←[33mWARN ←[0;39m ←[94mNET   ←[0;39m | ←[94mnet.components.JWT                      ←[0;39m : JWT Secret is less than 256 bits, padding with 0. PLEASE USE A STRONGER SECRET!
←[35m08-15 21:17:41←[0;39m ←[32mINFO ←[0;39m ←[94mNET   ←[0;39m | ←[94mnet.components.JWT                      ←[0;39m : JWT Service Enabled
←[35m08-15 21:17:42←[0;39m ←[32mINFO ←[0;39m ←[94mNET   ←[0;39m | ←[94mnet.components.GeoIP                    ←[0;39m : GeoIP Service Enabled
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/chu3/music.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/chu3/items.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/mai2/music.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/mai2/items.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/ongeki/music.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/ongeki/items.json is not found
←[35m08-15 21:17:42←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mext.Ext                                 ←[0;39m : Resource /meta/wacca/music.json is not found
←[35m08-15 21:17:43←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.h.engine.jdbc.spi.SqlExceptionHelper  ←[0;39m : SQL Error: 1, SQLState: null
←[35m08-15 21:17:43←[0;39m ←[31mERROR←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.h.engine.jdbc.spi.SqlExceptionHelper  ←[0;39m : [SQLITE_ERROR] SQL error or missing database (no such column: c1_0.net_user_id)
←[35m08-15 21:17:43←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mConfigServletWebServerApplicationContext←[0;39m : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'migrations': Invocation of init method failed
←[35m08-15 21:17:43←[0;39m ←[33mWARN ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.s.b.f.support.DisposableBeanAdapter   ←[0;39m : Invocation of close method failed on bean with name 'defaultMailer': org.simplejavamail.internal.moduleloader.ModuleLoaderException: Batch module not found, make sure it is on the classpath (https://github.com/bbottema/simple-java-mail/tree/develop/modules/batch-module)
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mj.LocalContainerEntityManagerFactoryBean←[0;39m : Closing JPA EntityManagerFactory for persistence unit 'default'
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mcom.zaxxer.hikari.HikariDataSource      ←[0;39m : HikariPool-1 - Shutdown initiated...
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mcom.zaxxer.hikari.HikariDataSource      ←[0;39m : HikariPool-1 - Shutdown completed.
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37morg.eclipse.jetty.server.Server         ←[0;39m : Stopped oejs.Server@2352c21f{STOPPING}[12.0.6,sto=0]
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.e.j.e.servlet.ServletContextHandler   ←[0;39m : Stopped osbwej.JettyEmbeddedWebAppContext@40fd1a78{application,/,b=file:/C:/Users/Sebastian/AppData/Local/Temp/jetty-docbase.80.4833982340918080819/,a=AVAILABLE,h=oeje10s.SessionHandler@53b7f08{STOPPED}}
←[35m08-15 21:17:43←[0;39m ←[32mINFO ←[0;39m ←[37mSYSTEM←[0;39m | ←[37m.s.b.a.l.ConditionEvaluationReportLogger←[0;39m :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
←[35m08-15 21:17:43←[0;39m ←[31mERROR←[0;39m ←[37mSYSTEM←[0;39m | ←[37mo.s.boot.SpringApplication              ←[0;39m : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'migrations': Invocation of init method failed
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at icu.samnyan.aqua.EntryKt.main(Entry.kt:19)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.springframework.orm.jpa.JpaSystemException: could not prepare statement [[SQLITE_ERROR] SQL error or missing database (no such column: c1_0.net_user_id)] [select c1_0.id,c1_0.access_time,c1_0.net_user_id,c1_0.ext_id,c1_0.is_ghost,c1_0.luid,c1_0.ranking_banned,c1_0.register_time from sega_card c1_0]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:341)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:164)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
        at jdk.proxy2/jdk.proxy2.$Proxy178.findAll(Unknown Source)
        at icu.samnyan.aqua.net.Migrations.migrateSignedID(Migrations.kt:44)
        at icu.samnyan.aqua.net.Migrations.migrate(Migrations.kt:32)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
        ... 23 common frames omitted
Caused by: org.hibernate.exception.GenericJDBCException: could not prepare statement [[SQLITE_ERROR] SQL error or missing database (no such column: c1_0.net_user_id)] [select c1_0.id,c1_0.access_time,c1_0.net_user_id,c1_0.ext_id,c1_0.is_ghost,c1_0.luid,c1_0.ranking_banned,c1_0.register_time from sega_card c1_0]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:194)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)
        at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
        at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:202)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:137)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:362)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:303)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:509)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)
        at org.hibernate.query.Query.getResultList(Query.java:120)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:383)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:1)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        ... 37 common frames omitted
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: c1_0.net_user_id)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)
        ... 79 common frames omitted

Press any key to continue . . .
```

**Comment by clansty** [comment]
SQLite support is broken and will be removedplease use mariadb

**Comment by Sebakan** [comment]
> SQLite support is broken and will be removedplease use mariadb

oh i figured out. I was following the instruction in the readme for the v1 dev version but working over the stable version. Thanks!
