### ISSUE TITLE
Ongeki 1.45 TITLE SERVER BAD

### ISSUE THREAD

**Issue by kanon511** [hykilpikonna/AquaDX#72]
I built the project myself and used it to run a local server. It runs fine on ChuLum, but I get the title server BAD when running Ongeki version 1.45. My Ongeki works fine on your https://aquadx.net/ server, and also works on the older version of aqua 0.45.0 (although with missing data). Am I missing something?
![image](https://github.com/user-attachments/assets/3472fb2e-51dd-41a6-a749-0751bb503482)
[application.properties](https://github.com/user-attachments/files/17470068/application.properties.txt)
<details>
  <summary>open</summary>
┏━┓         ┳━┓━┓┏━
┣━┫┏━┓┓ ┏┏━┓┃ ┃ ┣┫
┛ ┗┗━┫┗━┻┗━┻┻━┛━┛┗━
     ┗
AquaDX Local Arcade Server
Version: 1.0.0 (Built on 2024-10-21 14:42:12 UTC)

This is a free open-source software. If you paid for it, you were scammed.

[Self testing]
Aime DB : Port 22345 ?
Billing : Port 8443 ?
ALL.Net : Port 80 ?? ?
> Self-tests failed.
ALL.Net host is currently using loopback address.
Game might not connect to server with this. If it was not intentional, please edit configuration file.

10-22 12:29:09 WARN  SYSTEM | s.s.a.ScheduledAnnotationReactiveSupport : Unexpected error occurred in scheduled reactive task

io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://api.openai.com/v1/moderations, connect_timeout=unknown ms]
        at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:213)
        at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:210)
        at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:268)
        at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:257)
        at io.ktor.client.engine.cio.Endpoint.access$connect(Endpoint.kt:25)
        at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Endpoint.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

10-22 12:29:09 INFO  ALLNET | allnet.KeychipSessionService             : !!! Keychip session cleanup !!!
10-22 12:29:23 INFO  ALLNET | allnet.AllNet                            : AllNet /PowerOn : {game_id=SDDT, ver=1.45, serial=A8042990679, ip=192.168.1.6, firm_ver=50000, boot_ver=0000, encode=UTF-8, format_ver=3, hops=1, token=2313202871}
10-22 12:29:23 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, name=, place_id=123, region0=1, region_name0=W, region_name1=X, region_name2=Y, region_name3=Z, country=JPN, nickname=AquaDX, uri=http://localhost:80/g/ongeki/, host=localhost, allnet_id=456, client_timezone=+0900, utc_time=2024-10-22T04:29:23Z, setting=, res_ver=3, token=2313202871}
10-22 12:29:23 INFO  AIMEDB | aimedb.AimeDB                            : AimeDB /Campaign : (game SDDT, keychip A8042990679)
10-22 12:29:23 INFO  ALLNET | allnet.AllNet                            : AllNet /DownloadOrder : {game_id=SDDT, ver=1.45, serial=A8042990679, encode=UTF-8}
10-22 12:29:23 INFO  ALLNET | allnet.AllNet                            : > Response: {stat=1, serial=A8042990679}
</details>

**Comment by hykilpikonna** [comment]
Please read the logs. It says:

```
Self-tests failed.
ALL.Net host is currently using loopback address.
Game might not connect to server with this. If it was not intentional, please edit configuration file.
```

Changing localhost to your LAN ip like 192.168.something might help.

Please reopen the issue if this doesn't work.
